"use client";

import { useMemo, useState } from "react";
import { Activity, Download, RotateCcw, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Kicker, Panel } from "@/components/ui/panel";
import { calculateIntegratedSensitivity, createDefaultIntegratedMarketScenario, serializeIntegratedScenario, simulateIntegratedScenario, type MarketScenarioId, type SimulationMode } from "@/lib/market-fit";

const integer = (value: number) => value.toLocaleString("en-US", { maximumFractionDigits: 0 });
const number = (value: number) => value.toLocaleString("en-US", { maximumFractionDigits: 1 });
const usd = (value: number | null) => value === null ? "Needs verified input" : `$${integer(value)}`;

function Metric({ label, value }: { label: string; value: string }) {
  return <div className="rounded-lg border border-white/10 bg-white/[0.03] p-3"><p className="text-[11px] text-slate-400">{label}</p><p className="mt-1 text-lg font-semibold text-white">{value}</p></div>;
}

export function IntegratedMarketFitPanel({ scenarioOverride }: { scenarioOverride?: ReturnType<typeof createDefaultIntegratedMarketScenario> | null }) {
  const [scenarioId, setScenarioId] = useState<MarketScenarioId>("base");
  const [mode, setMode] = useState<SimulationMode>("coupled");
  const [month, setMonth] = useState(1);
  const defaultScenario = useMemo(() => createDefaultIntegratedMarketScenario(scenarioId), [scenarioId]);
  const scenario = scenarioOverride ?? defaultScenario;
  const result = useMemo(() => simulateIntegratedScenario(scenario, mode), [scenario, mode]);
  const snapshot = result.snapshots[month - 1];
  const sensitivity = useMemo(() => calculateIntegratedSensitivity(scenario, mode), [scenario, mode]);
  const exportScenario = () => { const blob = new Blob([serializeIntegratedScenario(scenario)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `skyloop-${scenarioId}-integrated-scenario.json`; link.click(); URL.revokeObjectURL(url); };
  const maxRevenue = Math.max(...result.snapshots.map((entry) => entry.revenueUsd), 1);

  return <section aria-labelledby="integrated-simulator-title" className="space-y-6">
    <Panel className="border-cyan-signal/25 bg-slate-950/80"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><Kicker className="text-cyan-signal">Integrated Money Universe × Skyloop</Kicker><h2 id="integrated-simulator-title" className="mt-2 text-2xl font-semibold text-white">Scenario command center</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">A deterministic 36-month bridge. Money Universe owns macro calculations; Market Fit owns funnel and unit economics. Every result is simulated and evidence-labeled.</p></div><div className="flex flex-wrap gap-2"><select aria-label="Integrated scenario" value={scenarioId} onChange={(event) => { setScenarioId(event.target.value as MarketScenarioId); setMonth(1); }} className="rounded-md border border-white/15 bg-slate-900 px-3 py-2 text-sm text-white"><option value="conservative">Conservative</option><option value="base">Base</option><option value="optimistic">Optimistic</option></select><Button type="button" variant={mode === "base" ? "default" : "outline"} onClick={() => setMode("base")}>Base only</Button><Button type="button" variant={mode === "coupled" ? "default" : "outline"} onClick={() => setMode("coupled")}>Coupled</Button><Button type="button" variant="outline" onClick={() => { setScenarioId("base"); setMode("coupled"); setMonth(1); }}><RotateCcw className="size-4" /> Reset</Button><Button type="button" variant="outline" onClick={exportScenario}><Download className="size-4" /> Export JSON</Button></div></div><div className="mt-5 rounded-lg border border-white/10 bg-white/[0.03] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><label htmlFor="simulation-month" className="text-sm font-medium text-white">Month {month} of {scenario.horizon}</label><span className="text-xs text-cyan-signal">{mode === "coupled" ? "macro feedback enabled" : "base macro held constant"}</span></div><input id="simulation-month" type="range" min="1" max={scenario.horizon} value={month} onChange={(event) => setMonth(Number(event.target.value))} className="mt-3 w-full accent-cyan-400" /></div></Panel>
    <div className="grid gap-6 xl:grid-cols-3"><Panel><Kicker>Macro bridge</Kicker><h3 className="mt-2 text-lg font-semibold text-white">Money Universe → demand</h3><div className="mt-4 grid grid-cols-2 gap-2"><Metric label="Inflation" value={number(snapshot.macroOutputs.inflation)} /><Metric label="Trade" value={number(snapshot.macroOutputs.trade)} /><Metric label="Stability" value={number(snapshot.macroOutputs.stability)} /><Metric label="Wealth" value={number(snapshot.macroOutputs.wealth)} /></div><p className="mt-4 text-xs leading-5 text-slate-400">Demand × <strong className="text-white">{snapshot.modifiers.demandMultiplier}</strong> · retention × <strong className="text-white">{snapshot.modifiers.retentionMultiplier}</strong> · cost × <strong className="text-white">{snapshot.modifiers.costMultiplier}</strong><br />Trust {number(snapshot.macroInputs.trust)} → {number(snapshot.derivedMacroInputs.trust)} · productivity {number(snapshot.macroInputs.productivity)} → {number(snapshot.derivedMacroInputs.productivity)}</p></Panel><Panel><Kicker>Product funnel</Kicker><h3 className="mt-2 text-lg font-semibold text-white">Understanding → retained user</h3><div className="mt-4 grid grid-cols-2 gap-2"><Metric label="Visitors" value={integer(snapshot.product.visits)} /><Metric label="Activated" value={integer(snapshot.product.activatedUsers)} /><Metric label="New paid" value={integer(snapshot.product.newPaidUsers)} /><Metric label="Active paid" value={integer(snapshot.product.activePaidUsers)} /><Metric label="Churned" value={integer(snapshot.product.churnedUsers)} /><Metric label="Visuals" value={integer(snapshot.product.freeVisuals + snapshot.product.paidVisuals)} /></div></Panel><Panel><Kicker>Cost laboratory</Kicker><h3 className="mt-2 text-lg font-semibold text-white">API evidence gate</h3><div className="mt-4 rounded-lg border border-amber-300/20 bg-amber-300/[0.05] p-3 text-sm text-amber-100"><p className="font-medium">{snapshot.apiCost.available ? `Cost / visual: ${usd(snapshot.apiCost.costPerVisualUsd)}` : "API cost unavailable"}</p><p className="mt-1 text-xs opacity-75">{snapshot.apiCost.reason ?? "Verified catalog entries are active."}</p></div><div className="mt-4 space-y-2 text-xs text-slate-400">{scenario.apiCostInputs.models.map((model) => <div key={model.id} className="flex justify-between gap-2"><span>{model.model} · {model.mixPercent * 100}%</span><span className={model.status === "verified" ? "text-lime-300" : "text-amber-300"}>{model.status}</span></div>)}<p className="pt-2">Total API cost: {usd(snapshot.product.verifiedApiCostUsd)} · known costs: {usd(snapshot.product.totalKnownCostUsd)}</p></div></Panel></div>
    <div className="grid gap-6 lg:grid-cols-[1.4fr_1fr]"><Panel><div className="flex items-center gap-2"><Activity className="size-5 text-cyan-signal" /><div><Kicker>Money loop · month {month}</Kicker><h3 className="mt-1 text-lg font-semibold text-white">Users → revenue → cost → feedback</h3></div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Revenue" value={usd(snapshot.revenueUsd)} /><Metric label="Total cost" value={usd(snapshot.totalCostUsd)} /><Metric label="Gross profit" value={usd(snapshot.grossProfitUsd)} /><Metric label="Runway" value={snapshot.runwayMonths === null ? "Needs evidence" : `${snapshot.runwayMonths} mo`} /></div><div className="mt-5 flex h-24 items-end gap-1" aria-label="36 month revenue chart">{result.snapshots.map((item) => <div key={item.month} title={`Month ${item.month}: ${usd(item.revenueUsd)}`} className="min-w-0 flex-1 rounded-t bg-cyan-signal/60" style={{ height: `${Math.max(4, item.revenueUsd / maxRevenue * 100)}%` }} />)}</div></Panel><Panel><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-amber-300" /><div><Kicker>Review copilot</Kicker><h3 className="mt-1 text-lg font-semibold text-white">Blocking findings</h3></div></div><ul className="mt-4 space-y-3">{result.findings.map((finding) => <li key={`${finding.severity}-${finding.message}`} className="rounded-lg border border-white/10 p-3"><p className={finding.severity === "blocking" ? "text-rose-200" : finding.severity === "warning" ? "text-amber-200" : "text-cyan-200"}>{finding.severity}: {finding.message}</p><p className="mt-1 text-xs text-slate-500">{finding.action}</p></li>)}</ul><div className="mt-4 rounded-lg border border-white/10 p-3 text-xs text-slate-400">Overlay: adoption {number(snapshot.overlay.adoptionSignal)} · productivity +{number(snapshot.overlay.knowledgeProductivitySignal)} · trust {number(snapshot.overlay.trustSignal)} · confidence {snapshot.overlay.confidence}</div></Panel></div>
    <Panel><Kicker>Sensitivity laboratory</Kicker><h3 className="mt-2 text-lg font-semibold text-white">What changes the decision most?</h3><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{sensitivity.map((item) => <div key={item.parameter} className="rounded-lg border border-white/10 p-3"><p className="text-xs text-slate-400">{item.parameter}</p><p className="mt-1 text-sm font-medium text-amber-300">{item.metric === "activePaidUsers" ? `${item.impact.toFixed(0)} paid users` : usd(item.impact)}</p><p className="mt-1 text-[10px] text-slate-500">+10% test · {item.direction}</p></div>)}</div><details className="mt-4 rounded-lg border border-white/10 p-3"><summary className="cursor-pointer text-sm text-white">Show contract and evidence boundary</summary><div className="mt-3 grid gap-2 text-xs leading-5 text-slate-400 sm:grid-cols-2"><p>Macro source: Money Universe · simulated</p><p>Product source: Market Fit · simulated</p><p>Bridge policy: {scenario.bridgePolicy.version} · versioned</p><p>API pricing: dated official sources required · current fixture unverified</p><p>Persistence: local only · no database, billing, customer data, or API keys</p><p>Release: simulator never claims product-market fit</p></div></details></Panel>
  </section>;
}
