"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowRight, Beaker, CircleDollarSign, FlaskConical, Gauge, LockKeyhole, Route, ShieldCheck, Sparkles } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Kicker, MetricBar, Panel } from "@/components/ui/panel";
import { Button } from "@/components/ui/button";
import { IntegratedMarketFitPanel } from "./integrated-simulator-panel";
import { MathsAIScenarioOptimizer } from "./maths-ai-scenario-optimizer";
import { MarketAnalysisPanel } from "./market-analysis-panel";
import { calculateMarketFitScenario, createMarketFitReviewFindings, distributionChannels, marketCostCatalog, marketExperiments, marketScenarios, type IntegratedMarketScenario, type MarketScenarioId } from "@/lib/market-fit";

const integer = (value: number) => value.toLocaleString("en-US", { maximumFractionDigits: 0 });
const money = (value: number | null) => value === null ? "Needs verified input" : `$${integer(value)}`;
const percent = (value: number | null) => value === null ? "Needs evidence" : `${value.toFixed(1)}%`;

function Metric({ label, value, detail }: { label: string; value: string; detail?: string }) {
  return <div className="rounded-lg border border-white/10 bg-white/[0.03] p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-2 text-xl font-semibold text-white">{value}</p>{detail && <p className="mt-1 text-xs text-slate-500">{detail}</p>}</div>;
}

export function MarketFitPortal() {
  const [scenarioId, setScenarioId] = useState<MarketScenarioId>("base");
  const [integratedOverride, setIntegratedOverride] = useState<IntegratedMarketScenario | null>(null);
  const scenario = marketScenarios[scenarioId];
  const outputs = useMemo(() => calculateMarketFitScenario(scenario, marketCostCatalog), [scenario]);
  const findings = useMemo(() => createMarketFitReviewFindings(scenario, marketCostCatalog, outputs), [scenario, outputs]);

  return <AppShell active="/market-fit">
    <div className="mb-6"><IntegratedMarketFitPanel scenarioOverride={integratedOverride} /><MarketAnalysisPanel /><MathsAIScenarioOptimizer onApplyScenario={setIntegratedOverride} /></div>
    <div className="relative overflow-hidden rounded-xl border border-cyan-signal/20 bg-slate-950/70 p-6 sm:p-8"><div className="absolute -right-20 -top-24 size-72 rounded-full bg-cyan-signal/10 blur-3xl" /><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><Kicker className="text-cyan-signal">Private AGI OS Portal · Skyloop Market Fit</Kicker><h1 className="mt-3 max-w-4xl text-3xl font-semibold tracking-tight text-white sm:text-5xl">Simulate the money loop before you spend real money.</h1><p className="mt-4 max-w-3xl text-base leading-7 text-slate-300">A decision laboratory for audience, activation, free value, pricing, distribution, API cost, retention, and Version 1 release evidence.</p></div><div className="rounded-lg border border-amber-300/30 bg-amber-300/[0.08] p-4 text-sm text-amber-100"><div className="flex items-center gap-2 font-semibold"><LockKeyhole className="size-4" /> Internal simulator</div><p className="mt-2 max-w-xs text-xs leading-5 text-amber-100/70">No billing, payment credentials, campaigns, or external data ingestion are active.</p></div></div></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[300px_1fr]"><Panel><Kicker>Scenario controls</Kicker><label className="mt-5 block text-sm font-medium text-white" htmlFor="market-scenario">Operating scenario</label><select id="market-scenario" value={scenarioId} onChange={(event) => setScenarioId(event.target.value as MarketScenarioId)} className="mt-2 w-full rounded-md border border-white/15 bg-slate-900 px-3 py-2 text-sm text-white"><option value="conservative">Conservative</option><option value="base">Base</option><option value="optimistic">Optimistic</option></select><p className="mt-3 text-xs leading-5 text-slate-400">All values are local simulated assumptions. They are not product-market-fit evidence.</p><div className="mt-6 space-y-4"><MetricBar label="Activation rate" value={scenario.assumptions.activationRate * 100} /><MetricBar label="Repeat-session rate" value={scenario.assumptions.repeatSessionRate * 100} /><MetricBar label="Paid conversion" value={scenario.assumptions.paidConversionRate * 100} /><MetricBar label="Monthly churn" value={scenario.assumptions.monthlyChurnRate * 100} /></div><Button type="button" variant="outline" className="mt-6 w-full" onClick={() => setScenarioId("base")}><Gauge className="size-4" /> Reset to base</Button></Panel>
      <div className="space-y-6"><Panel><div className="flex flex-wrap items-start justify-between gap-4"><div><Kicker>Decision summary</Kicker><h2 className="mt-2 text-2xl font-semibold text-white">{scenario.label} scenario</h2><p className="mt-2 text-sm text-slate-400">Primary activation event: a learner completes their first successful visual explanation.</p></div><div className="rounded-lg border border-rose-300/25 bg-rose-300/[0.06] px-3 py-2 text-xs text-rose-100">Release decision: evidence required</div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Monthly visits" value={integer(outputs.visits)} /><Metric label="Activated users" value={integer(outputs.activatedUsers)} detail="First understanding moment" /><Metric label="Paid users" value={integer(outputs.paidUsers)} /><Metric label="MRR" value={money(outputs.monthlyRevenueUsd)} detail="Simulated revenue" /></div></Panel>
        <Panel><div className="flex items-center gap-2"><Route className="size-5 text-cyan-signal" /><div><Kicker>Product funnel</Kicker><h2 className="mt-1 text-xl font-semibold text-white">Visitor → retained subscriber</h2></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Visits" value={integer(outputs.visits)} /><Metric label="Signups" value={integer(outputs.signups)} /><Metric label="Activated" value={integer(outputs.activatedUsers)} /><Metric label="Repeat" value={integer(outputs.repeatUsers)} /><Metric label="Paid" value={integer(outputs.paidUsers)} /></div></Panel>
        <Panel><div className="flex items-center gap-2"><CircleDollarSign className="size-5 text-lime-signal" /><div><Kicker>Unit economics</Kicker><h2 className="mt-1 text-xl font-semibold text-white">Revenue is visible; profitability waits for verified costs</h2></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="ARR" value={money(outputs.annualizedRevenueUsd)} /><Metric label="Known monthly cost" value={money(outputs.totalKnownCostUsd)} /><Metric label="Gross profit" value={money(outputs.grossProfitUsd)} detail="Blocked until API price verified" /><Metric label="Gross margin" value={percent(outputs.grossMarginPercent)} /></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric label="LTV" value={money(outputs.ltvUsd)} /><Metric label="LTV / CAC" value={outputs.ltvToCac === null ? "Needs evidence" : `${outputs.ltvToCac}×`} /><Metric label="CAC payback" value={outputs.cacPaybackMonths === null ? "Needs evidence" : `${outputs.cacPaybackMonths} months`} /></div></Panel></div></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel><div className="flex items-center gap-2"><AlertTriangle className="size-5 text-amber-300" /><div><Kicker>Cost catalog</Kicker><h2 className="mt-1 text-xl font-semibold text-white">Verified API pricing gate</h2></div></div><div className="mt-4 rounded-lg border border-amber-300/20 bg-amber-300/[0.06] p-4 text-sm text-amber-100"><p className="font-medium">API cost: {outputs.apiCostStatus === "available" ? money(outputs.verifiedApiCostUsd) : "unavailable"}</p><p className="mt-2 text-xs leading-5 text-amber-100/70">No provider price has been entered. Add provider, model, input/output rates, source URL, effective date, and verification date before using margin or break-even outputs.</p></div><div className="mt-4 divide-y divide-white/10 text-sm"><div className="flex justify-between py-2 text-slate-400"><span>Free visual operations</span><span className="text-white">{integer(outputs.freeVisuals)}</span></div><div className="flex justify-between py-2 text-slate-400"><span>Paid visual operations</span><span className="text-white">{integer(outputs.paidVisuals)}</span></div><div className="flex justify-between py-2 text-slate-400"><span>Infrastructure + support + acquisition</span><span className="text-white">{money(outputs.totalKnownCostUsd)}</span></div></div></Panel><Panel><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-cyan-signal" /><div><Kicker>Review copilot</Kicker><h2 className="mt-1 text-xl font-semibold text-white">Decision guardrails</h2></div></div><ul className="mt-4 space-y-3">{findings.map((finding) => <li key={`${finding.severity}-${finding.message}`} className="rounded-lg border border-white/10 bg-white/[0.03] p-3"><p className={finding.severity === "blocking" ? "font-medium text-rose-200" : finding.severity === "warning" ? "font-medium text-amber-200" : "font-medium text-cyan-200"}>{finding.severity}: {finding.message}</p><p className="mt-1 text-xs leading-5 text-slate-400">Next: {finding.action}</p></li>)}</ul></Panel></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel><div className="flex items-center gap-2"><FlaskConical className="size-5 text-purple-300" /><div><Kicker>Experiment queue</Kicker><h2 className="mt-1 text-xl font-semibold text-white">Learn before scaling</h2></div></div><div className="mt-4 space-y-3">{marketExperiments.map((experiment) => <div key={experiment.id} className="rounded-lg border border-white/10 p-3"><div className="flex items-start justify-between gap-3"><h3 className="text-sm font-semibold text-white">{experiment.name}</h3><span className="rounded-full border border-white/15 px-2 py-1 text-[10px] uppercase tracking-wide text-slate-400">{experiment.status}</span></div><p className="mt-2 text-xs leading-5 text-slate-400">{experiment.hypothesis}</p><p className="mt-2 text-xs text-slate-500">Success: {experiment.successMetric} · Guardrail: {experiment.guardrailMetric}</p></div>)}</div></Panel><Panel><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-center gap-2"><Sparkles className="size-5 text-cyan-signal" /><div><Kicker>Distribution planner</Kicker><h2 className="mt-1 text-xl font-semibold text-white">Optimize for learning speed</h2></div></div><Link href="/distribution" className="inline-flex items-center gap-2 rounded-md border border-cyan-signal/30 bg-cyan-signal/10 px-3 py-2 text-xs font-semibold text-cyan-signal hover:bg-cyan-signal/15">Open Distribution <ArrowRight className="size-3.5" /></Link></div><div className="mt-4 space-y-3">{distributionChannels.map((channel) => <div key={channel.id} className="rounded-lg border border-white/10 p-3"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-semibold text-white">{channel.label}</h3><span className="text-xs text-cyan-signal">{channel.learningSpeed}</span></div><p className="mt-1 text-xs text-slate-400">{channel.audience} · {channel.format}</p><p className="mt-2 text-xs leading-5 text-slate-500">Next test: {channel.nextTest}</p></div>)}</div></Panel></div>
    <Panel className="mt-6"><div className="flex items-center gap-2"><Beaker className="size-5 text-lime-signal" /><div><Kicker>Release gate</Kicker><h2 className="mt-1 text-xl font-semibold text-white">Skyloop Version 1 is not approved by simulation alone</h2></div></div><div className="mt-4 grid gap-3 text-sm text-slate-300 md:grid-cols-3"><div className="rounded-lg border border-white/10 p-4"><p className="font-medium text-white">Measured</p><p className="mt-2 text-xs leading-5 text-slate-400">Real activation, retention, cost, and interview evidence.</p></div><div className="rounded-lg border border-white/10 p-4"><p className="font-medium text-white">Simulated</p><p className="mt-2 text-xs leading-5 text-slate-400">Scenario values shown above for decision rehearsal only.</p></div><div className="rounded-lg border border-white/10 p-4"><p className="font-medium text-white">Required next</p><p className="mt-2 text-xs leading-5 text-slate-400">Run first-understanding and pricing experiments, then enter verified cost data.</p></div></div></Panel>
  </AppShell>;
}
