"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Download, Pause, Play, RotateCcw, ShieldAlert, Square, WandSparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Kicker, Panel } from "@/components/ui/panel";
import { applyOptimizationParameters, candidateSensitivity, createDefaultIntegratedMarketScenario, DEFAULT_MARKET_OPTIMIZATION_CONFIG, optimizeMarketScenario, serializeMarketOptimizationCandidate, type MarketObjectiveWeights, type MarketOptimizationCandidate, type MarketOptimizationConfig, type MarketOptimizationReport, type MarketScenarioId, type SimulationMode } from "@/lib/market-fit";

const objectiveLabels: Array<[keyof MarketObjectiveWeights, string]> = [["activation", "Activation"], ["retention", "Retention"], ["paidConversion", "Paid conversion"], ["grossMargin", "Gross margin"], ["runway", "Runway"], ["apiEfficiency", "API efficiency"], ["evidenceQuality", "Evidence quality"], ["assumptionRisk", "Assumption safety"]];
const score = (value: number) => `${value.toFixed(1)}`;

export function MathsAIScenarioOptimizer({ onApplyScenario }: { onApplyScenario: (scenario: ReturnType<typeof createDefaultIntegratedMarketScenario>) => void }) {
  const [scenarioId, setScenarioId] = useState<MarketScenarioId>("base");
  const [mode, setMode] = useState<SimulationMode>("coupled");
  const [config, setConfig] = useState<MarketOptimizationConfig>(DEFAULT_MARKET_OPTIMIZATION_CONFIG);
  const [report, setReport] = useState<MarketOptimizationReport | null>(null);
  const [selected, setSelected] = useState<MarketOptimizationCandidate | null>(null);
  const [applied, setApplied] = useState<MarketOptimizationCandidate | null>(null);
  const pauseRef = useRef(false);
  const stopRef = useRef(false);
  const scenario = useMemo(() => createDefaultIntegratedMarketScenario(scenarioId), [scenarioId]);
  const appliedPreview = useMemo(() => applied ? applyOptimizationParameters(scenario, applied.parameters) : scenario, [applied, scenario]);
  const appliedResult = useMemo(() => applied ? candidateSensitivity(scenario, applied) : [], [applied, scenario]);
  useEffect(() => { if (applied) onApplyScenario(appliedPreview); }, [applied, appliedPreview, onApplyScenario]);
  const updateWeight = (key: keyof MarketObjectiveWeights, value: string) => setConfig((current) => ({ ...current, objectiveWeights: { ...current.objectiveWeights, [key]: Math.max(0, Math.min(1, Number(value))) } }));
  const start = async () => { pauseRef.current = false; stopRef.current = false; setReport((current) => current ? { ...current, status: "running" } : null); const next = await optimizeMarketScenario(scenario, mode, config, { onProgress: setReport, shouldStop: () => stopRef.current, waitIfPaused: async () => { while (pauseRef.current && !stopRef.current) await new Promise<void>((resolve) => setTimeout(resolve, 100)); } }); setReport(next); setSelected(next.best); };
  const exportCandidate = () => { if (!selected) return; const blob = new Blob([serializeMarketOptimizationCandidate(selected)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${selected.id}-skyloop-market-fit-candidate.json`; link.click(); URL.revokeObjectURL(url); };
  return <Panel className="mt-6 border-lime-signal/25 bg-slate-950/80"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><Kicker className="text-lime-signal">Maths AI → Skyloop Market Fit</Kicker><h2 className="mt-2 text-2xl font-semibold text-white">Maths AI Scenario Optimizer</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Bounded candidate search over the existing Market Fit simulator. This is a review copilot: it cannot publish, bill, spend, or claim product-market fit.</p></div><div className="flex flex-wrap gap-2"><select aria-label="Optimizer starting scenario" value={scenarioId} onChange={(event) => { setScenarioId(event.target.value as MarketScenarioId); setReport(null); setSelected(null); setApplied(null); }} className="rounded-md border border-white/15 bg-slate-900 px-3 py-2 text-sm text-white"><option value="conservative">Conservative</option><option value="base">Base</option><option value="optimistic">Optimistic</option></select><Button type="button" variant={mode === "base" ? "primary" : "outline"} onClick={() => setMode("base")}>Base</Button><Button type="button" variant={mode === "coupled" ? "primary" : "outline"} onClick={() => setMode("coupled")}>Coupled</Button><Button type="button" variant="outline" onClick={() => { stopRef.current = true; pauseRef.current = false; setReport(null); setSelected(null); setApplied(null); }}><RotateCcw className="size-4" /> Reset</Button></div></div>
    <div className="mt-5 grid gap-6 xl:grid-cols-[280px_1fr]"><div className="space-y-4 rounded-lg border border-white/10 bg-white/[0.03] p-4"><div className="flex items-center justify-between"><Kicker>Search controls</Kicker><span className="text-[10px] text-slate-500">bounded</span></div>{([["populationSize", "Population", 4, 32], ["maxGenerations", "Generations", 1, 30], ["maxSimulations", "Simulations", 4, 500], ["targetScore", "Target score", 1, 100], ["patience", "Stagnation", 1, 10]] as Array<[keyof MarketOptimizationConfig, string, number, number]>).map(([key, label, min, max]) => <label key={key} className="block text-xs text-slate-400">{label}<input type="number" min={min} max={max} value={config[key] as number} onChange={(event) => setConfig((current) => ({ ...current, [key]: Number(event.target.value) }))} className="mt-1 h-8 w-full rounded border border-white/10 bg-slate-950 px-2 text-white" /></label>)}<div className="border-t border-white/10 pt-3"><p className="text-xs font-semibold text-white">Balanced objective weights</p>{objectiveLabels.map(([key, label]) => <label key={key} className="mt-2 block text-[11px] text-slate-400">{label} <span className="float-right text-cyan-signal">{config.objectiveWeights[key].toFixed(2)}</span><input type="range" min="0" max="1" step="0.01" value={config.objectiveWeights[key]} onChange={(event) => updateWeight(key, event.target.value)} className="mt-1 w-full accent-lime-300" /></label>)}</div><div className="flex flex-wrap gap-2"><Button type="button" onClick={() => void start()} disabled={report?.status === "running"}><Play className="size-4" /> Start</Button>{report?.status === "running" ? <Button type="button" variant="outline" onClick={() => { pauseRef.current = true; setReport((current) => current ? { ...current, status: "paused" } : current); }}><Pause className="size-4" /> Pause</Button> : null}{report?.status === "paused" ? <Button type="button" onClick={() => { pauseRef.current = false; setReport((current) => current ? { ...current, status: "running" } : current); }}><Play className="size-4" /> Resume</Button> : null}<Button type="button" variant="outline" onClick={() => { stopRef.current = true; pauseRef.current = false; }}><Square className="size-4" /> Stop</Button></div></div>
      <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-4"><Metric label="Status" value={report?.status ?? "idle"} /><Metric label="Generation" value={`${report?.generation ?? 0}`} /><Metric label="Simulations" value={`${report?.simulations ?? 0}`} /><Metric label="Best score" value={report?.best ? score(report.best.score) : "—"} /></div><div className="rounded-lg border border-white/10 bg-black/20 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><Kicker>Candidate ranking</Kicker><p className="mt-1 text-xs text-slate-500">Evidence-blocked candidates remain visible; they cannot make profitability claims.</p></div><div className="flex gap-2"><Button type="button" variant="outline" onClick={exportCandidate} disabled={!selected}><Download className="size-4" /> Export</Button><a href="/maths-ai" className="inline-flex h-10 items-center gap-2 rounded-md border border-cyan-signal/30 bg-cyan-signal/10 px-4 text-sm font-medium text-cyan-signal">Open Maths AI</a></div></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="text-slate-500"><tr><th className="p-2">Candidate</th><th className="p-2">Status</th><th className="p-2">Score</th><th className="p-2">Paid users</th><th className="p-2">Revenue</th><th className="p-2">API</th><th className="p-2">Action</th></tr></thead><tbody>{(report?.ranked ?? []).slice(0, 10).map((candidate) => <tr key={candidate.id} className={`border-t border-white/10 ${selected?.id === candidate.id ? "bg-cyan-signal/10" : ""}`}><td className="p-2 font-mono text-white">{candidate.id}<span className="ml-2 text-slate-500">g{candidate.generation}</span></td><td className="p-2"><span className={candidate.status === "rejected" ? "text-rose-300" : candidate.status === "needs-evidence" ? "text-amber-300" : "text-lime-300"}>{candidate.status}</span></td><td className="p-2 text-white">{score(candidate.score)}</td><td className="p-2 text-slate-300">{candidate.summary.finalPaidUsers}</td><td className="p-2 text-slate-300">${candidate.summary.finalRevenueUsd.toFixed(0)}</td><td className="p-2 text-amber-300">{candidate.summary.apiCostAvailable ? "verified" : "blocked"}</td><td className="p-2"><button type="button" className="text-cyan-signal underline" onClick={() => setSelected(candidate)}>Preview</button></td></tr>)}</tbody></table>{report?.ranked.length ? null : <p className="py-8 text-center text-sm text-slate-500">Start a bounded search to generate candidates.</p>}</div></div>{selected ? <CandidatePreview candidate={selected} scenario={scenario} applied={applied?.id === selected.id} onApply={() => setApplied(selected)} preview={appliedPreview} sensitivity={appliedResult} /> : null}</div></div>
    {report?.best?.status === "needs-evidence" ? <div className="mt-4 flex gap-3 rounded-lg border border-amber-300/20 bg-amber-300/[0.06] p-4 text-sm text-amber-100"><ShieldAlert className="size-5 shrink-0" /><p>Best candidate is previewable but API pricing is unverified. Gross profit, margin, and break-even remain blocked.</p></div> : null}
  </Panel>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-white/10 bg-white/[0.03] p-3"><p className="text-[11px] text-slate-400">{label}</p><p className="mt-1 text-lg font-semibold text-white">{value}</p></div>; }

function CandidatePreview({ candidate, scenario, applied, onApply, preview, sensitivity }: { candidate: MarketOptimizationCandidate; scenario: ReturnType<typeof createDefaultIntegratedMarketScenario>; applied: boolean; onApply: () => void; preview: ReturnType<typeof createDefaultIntegratedMarketScenario>; sensitivity: Array<{ parameter: string; impact: number }> }) {
  return <div className="mt-4 rounded-lg border border-cyan-signal/20 bg-cyan-signal/[0.04] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><Kicker>Candidate preview · {candidate.id}</Kicker><p className="mt-1 text-sm text-slate-300">Generation {candidate.generation} · {candidate.lineage.source} · {candidate.status}</p></div><Button type="button" onClick={onApply} disabled={applied}><WandSparkles className="size-4" /> {applied ? "Applied to private preview" : "Apply to simulator"}</Button></div><div className="mt-4 grid gap-2 sm:grid-cols-4"><Metric label="Score" value={candidate.score.toFixed(1)} /><Metric label="Final paid users" value={`${candidate.summary.finalPaidUsers}`} /><Metric label="Final revenue" value={`$${candidate.summary.finalRevenueUsd.toFixed(0)}`} /><Metric label="Gross profit" value={candidate.summary.finalGrossProfitUsd === null ? "Needs evidence" : `$${candidate.summary.finalGrossProfitUsd.toFixed(0)}`} /></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><div className="rounded border border-white/10 p-3 text-xs text-slate-400"><p className="font-semibold text-white">Objective breakdown</p>{objectiveLabels.map(([key, label]) => <p key={key} className="mt-1 flex justify-between"><span>{label}</span><span className="text-cyan-signal">{candidate.objectiveScores[key].toFixed(1)}</span></p>)}</div><div className="rounded border border-white/10 p-3 text-xs text-slate-400"><p className="font-semibold text-white">Sensitivity</p>{sensitivity.slice(0, 6).map((item) => <p key={item.parameter} className="mt-1 flex justify-between"><span>{item.parameter}</span><span className="text-amber-300">{item.impact.toFixed(1)}</span></p>)}<p className="mt-2 text-slate-500">Applied preview remains isolated from the original scenario.</p></div></div><details className="mt-4"><summary className="cursor-pointer text-xs text-slate-300">Show candidate parameters and constraints</summary><pre className="mt-2 overflow-auto rounded bg-black/30 p-3 text-[10px] text-slate-400">{JSON.stringify({ parameters: candidate.parameters, violations: candidate.constraintViolations, rejectionReasons: candidate.rejectionReasons, previewScenarioId: preview.id, sourceScenarioId: scenario.id }, null, 2)}</pre></details></div>;
}
